### ISSUE TITLE
Cert schema change: optional fields and multiple signatures

### ISSUE THREAD

**Issue by kimdhamilton** [blockchain-certificates/BlockcertsFramework-iOS#26]
The schema changes performed [here](https://github.com/blockchain-certificates/cert-schema/pull/20) allow the following in v1.2 certificates

- optional document.certificate.id
- optional document.verify.signer
- optional image:signature
- image:signature type is one of string (original type) or array, as follows:

```
"image:signature": [
         {
           "jobTitle": "President",
           "image": "data:image/png;base64,"
         },
         {
           "jobTitle": "Vice-President",
           "image": "data:image/png;base64,"
         }
       ]
```

**Comment by bedinotti** [comment]
* `image:signature` is now optional -- if it's missing, then no signature images will be shown. 
* `image:signature` now supports the array of images.
