### ISSUE TITLE
Build actions around Certificates

### ISSUE THREAD

**Issue by bedinotti** [blockchain-certificates/BlockcertsFramework-iOS#8]
- [x] Verify the certificate
- [ ] Revoke the certificate
- [x] Share the certificate

**Comment by bedinotti** [comment]
Preliminary work for Verify is complete. I seem to be hitting some weird network issues that @kimdhamilton is seeing too. So when I tap 'Verify' it just hangs and the UI forgets about it.

**Comment by bedinotti** [comment]
Share is implemented, although currently it only works with document providers (iCloud). We should circle back to this once we determine all the different avenues we want to support sharing.

Revoke is stubbed out as a `*Request` class, and the UI around calling it is completed. I just need to figure out how to have it spend bitcoin from the appropriate address to have the recipient effectively revoke the certificate.

**Comment by kimdhamilton** [comment]
Sounds good. Let me know if I can help with that

**Comment by bedinotti** [comment]
Verify and Share work currently. I'm going to file a separate issue to track getting the Revoke action to work, since it's out of scope for the October 2016 deadline.
