### ISSUE TITLE
Set up CI server

### ISSUE THREAD

**Issue by bedinotti** [blockchain-certificates/BlockcertsFramework-iOS#9]
Buddybuild? Xcode Server? Something that runs tests regularly.

**Comment by bedinotti** [comment]
We've selected TravisCI for this, since it seems to be super common for open source iOS projects.

We've got a branch that is messing with the config. As soon as we can get that branch to run & pass all our existing tests, we'll merge it to master and call this task done.

**Comment by kimdhamilton** [comment]
Thanks for sorting this out! I'll set up the other projects to use TravisCI as well, and then we can close out the entire CICD task from the schedule.

**Comment by bedinotti** [comment]
I'm going to call this done. We've got a large number of our projects up & running with TravisCI, and most of them are passing tests. I'd say we've solved the CI piece. :)
